language: generic 
sudo: required
service:
    - docker

before_install:
    - docker build -t test-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true test-docker-react npm run test
